### ISSUE TITLE
Support CODEOWNERS update based on repo-metadata.json for Python

### ISSUE THREAD

**Issue by Shabirmean** [googleapis/synthtool#1000]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but can be a friction point.

 **Describe the solution you'd like**
- Respect `codeowner_team` in `repo-metadata.json` to auto update CODEOWNERS for **Python**

 **Describe alternatives you've considered**
- N/A

 **Additional context**
- When updating the `repo-metadata.json` for the [python-binary-authorization repo](https://github.com/googleapis/python-binary-authorization) in [this PR](https://github.com/googleapis/python-binary-authorization/pull/14) the `CODEOWNERS` file had to be manually updated. Would be great if it was added to the sythtool to automatically process it.

**Comment by parthea** [comment]
Closing as obsolete as the codeowners file is autogenerated. https://github.com/googleapis/python-binary-authorization/blob/main/.github/CODEOWNERS#L6
