### ISSUE TITLE
There are 3 Python shards failing at once

### ISSUE THREAD

**Issue by sofisl** [googleapis/synthtool#1108]
In this [view](https://fusion.corp.google.com/label/268750848), there are 3 Python shards failing today. Overall, Python does not seem to be that healthy.

<img width="1578" alt="Screen Shot 2021-06-04 at 3 53 02 PM" src="https://user-images.githubusercontent.com/55454395/120861545-15925f80-c54d-11eb-9947-779bab8d87c5.png">

**Comment by sofisl** [comment]
It doesn't seem like this has improved at all on Monday: 

<img width="749" alt="Screen Shot 2021-06-07 at 12 15 27 PM" src="https://user-images.githubusercontent.com/55454395/121061962-24198a80-c78a-11eb-9a70-bfc149170aff.png">

**Comment by busunkim96** [comment]
Each shard only has one repo:

- [shard 3](https://fusion2.corp.google.com/invocations/dcff8465-13f4-4fd2-b21e-245fe76c83c0/targets): failing on 'google-cloud-python' which is just has README generation for the library list
- [shard 5](https://fusion2.corp.google.com/invocations/531348c3-4436-4e65-b39b-8046d5872533/targets): python-datastore has a pending PR to migrate to owlbot
- [shard 7](https://fusion2.corp.google.com/invocations/fec9ddf2-711d-4365-85cb-aa4abb840781/targets): python-grafeas has a pending PR to migrate to owlbot

**Comment by busunkim96** [comment]
Datastore is now fixed (by completing the owlbot migration 😄 )

**Comment by parthea** [comment]
Opened https://github.com/googleapis/google-cloud-python/pull/10551 to fix `google-cloud-python`.

**Comment by bcoe** [comment]
Just an update this morning, that we're continuing to see three python shards consistently failing ... all the more motivation to move to OwlBot 😛

**Comment by parthea** [comment]
I'm going to close this issue as all of the issues in https://github.com/googleapis/synthtool/issues/1108#issuecomment-856173156 have been addressed.
