### ISSUE TITLE
owlbot-nodejs creates READMEs with broken links

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#1121]
As seen in https://github.com/googleapis/nodejs-storage/pull/1310

The Owl Bot nodejs post processor [created links](https://github.com/googleapis/nodejs-storage/pull/1310/commits/03c9e7e8024848d71b9f77e5867d6be1fa664951#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R189) to the new samples.  However, because the PR was not yet merged, the links were actually broken.  The docs check failed and @shaffeeullah was prevented from merging the pull request.

This will be a common situation.  We must provide a common solution so that repo maintainers do not have to contact Yoshi team every time they add a sample.

**Comment by tmatsuo** [comment]
FWIW, snippet-bot has a label `snippet-bot:no-prefix-req` for ignoring a certain type of check.
I'm not sure how the link checker is implemented, but introducing a flag for ignoring an error, might work for many cases.

**Comment by SurferJeffAtGoogle** [comment]
@shaffeeullah, next time this happens, add the label `owl-bot:ignore` to your pull request and Owl Bot will stop updating it.

**Comment by sofisl** [comment]
This issue is going OOSLO soon.

**Comment by SurferJeffAtGoogle** [comment]
Let's call it fixed.  Please re-open if we see it again.
