### ISSUE TITLE
Open a bug when autosynth fails

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#124]
When autosynth runs and opens a PR, it's a beautiful thing.  But what happens when it fails?  Some of us are great at watching the logs and checking in to make sure it ran.  Others (ok, me) are awful at that and will just forget.  In the event that autosynth fails for a given repository, it would be very nice to open a bug on that repo with a copy of the log, and make it super clear it failed.  That way I can sleep at night knowing that if it failed, at least I know about it.

**Comment by kinwa91** [comment]
Honestly I haven’t been diligent in checking to make sure autosynth runs - largely due to it being a daily run, and I don’t have a routine to check every day.

Do we have any established notifications when autosynth has failed?

@JustinBeckwith are you proposing we have a bot that opens up issue when it fails? Or is this a manual thing?

**Comment by tmatsuo** [comment]
How about to add a build badge to autosynth job, then add the badge to the README of the doc?

**Comment by JustinBeckwith** [comment]
@tmatsuo that still won't give me a notification of any sort.  Keep in mind we have ~60 nodejs repos, so there's no single one to go see the status.

@kinwa91 We don't have an established notification that I know of.  That's why I want this issue to get opened for me automagically :)

**Comment by theacodes** [comment]
> Do we have any established notifications when autosynth has failed?

Autosynth jobs are high-priority and mailed to `yoshi-internal+kokoro-high-priority` if they fail.

> How about to add a build badge to autosynth job, then add the badge to the README of the doc?

I am strongly against having dynamic badges, especially for build statuses. If we're having trouble with people checking the fusion dashboard for synth failures, I don't have much confidence that they'll check the REMADE.

**Comment by tmatsuo** [comment]
Yeah, I personally often see the fusion dashboard and it works for me. For node, maybe it is suffice to have a better e-mail filter?

**Comment by tmatsuo** [comment]
I still think the build badge for autosynth job makes sense for repo like php, while I'm not proactively advocate it.

**Comment by theacodes** [comment]
This is implemented.
