### ISSUE TITLE
Gradle and SBT instructions incomplete with the Java libraries BOM

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/synthtool#1242]
See internal b/184734265.

The Java README template has incomplete SBT and Gradle includes:
https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/README.md

**Comment by anguillanneuf** [comment]
@BenWhitehead said SBT doesn't support BOMs. The dependencies should be included in the flattened pom. As an example: https://search.maven.org/artifact/com.google.cloud/google-cloud-pubsub/1.114.6/jar

**Comment by Neenu1995** [comment]
Closing this as a no-op.
