### ISSUE TITLE
Add help or docs for optional env vars.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/synthtool#128]
currently synthtool have envvars that can be used to do advanced things. One such feature is `export SYNTHTOOL_GOOGLEAPIS=~/.cache/synthtool/googleapis-private` which supports using a local git checkout. There are others such as `SYNTHTOOL_ARTMAN_VERSION` or `AUTOSYNTH_USE_SSH`.

Improving the documentation for these could assist users.

**Comment by theacodes** [comment]
With #130, we should move these to arguments as well, so they'll be well documented in the commandline as well.
