### ISSUE TITLE
java postprocessor isn't hermetic for libraries-bom versions

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/synthtool#1318]
When OwlBot runs it's post processor it's possible that the version updates to the README.md for libraries-bom won't be properly proposed in the bump PR and will then be proposed multiple times in other PRs.

Example of java-storage PR where it received the README.md update even though the PR wasn't related to version bumps: https://github.com/googleapis/java-storage/pull/1186/files

<img width="834" alt="Screen Shot 2022-08-05 at 11 53 58 AM" src="https://user-images.githubusercontent.com/28604/183114911-201c662d-aac9-4853-a267-22ff4c7518c9.png">

Corresponding libraries-bom snippet at the time of postprocessor run for PR 1186: https://github.com/googleapis/java-storage/blob/1e55dba4cd5111472b9bb05db08ba7e47fafe762/samples/snippets/pom.xml#L27

**Comment by parthea** [comment]
Hi @Neenu1995 , this issue is out of SLO because it's marked as P1. Please could you take a look?

**Comment by Neenu1995** [comment]
I plan to a take a look in the coming weeks.

Mean while, downgrading it to p2 because it is no-blocking.

**Comment by suztomo** [comment]
I also observed the postprocessor touching the README.md's versions caused pull request conflict state in pull requests. A potential scenario:

1. Pull Request A is created. The postprocessor runs, modifying README.md to have libraries-bom 1.0.0. It's kept open.
2. Libraries BOM 1.1.0 is released
3. Pull Request B is created. The postprocessor runs, modifying README.md to have libraries-bom 1.1.0.
3. Pull Request B is merged.
4. Now Pull Request A is in conflict state at libraries BOM version in README.md.

In this scenario, adding "owlbot:run" label should resolve the conflict in Pull Request A.

@BenWhitehead Do you also think the annoyance of this OwlBot postprocessor is at the conflicts? Or do you observe something worse?

**Comment by BenWhitehead** [comment]
In my mind it's less about maneuvering around how to get a conflicted PR unstuck, and more the fact that docs updates that should happen along with a dependency bump are not isolated to that dependency bump PR. Instead every PR that happens to run between the time of release and the time of the dependency bump PR will have this proposed change.

**Comment by suztomo** [comment]
Thanks.

Idea memo: java postprocessor should upgrade the libraries-bom version only when a pull request is upgrading the libraries-bom version in samples. (Or just files in samples)

Todo on me: read the postprocessor code to determine the logic of README updates.

**Comment by suztomo** [comment]
Survey result:

- The postprocessor's [entrypoint.sh](https://github.com/googleapis/synthtool/blob/48f8857c642792150e2474418b1dbf545c162f8d/docker/owlbot/java/bin/entrypoint.sh#L22) calls write_templates.sh
- write_templates.sh calls owlbot.py in the repository. Note that this owlbot.py plays an important role to bring OwlBot changes from google3 from its staging directory.
- owlbot.py calls [`java.common_templates`](https://github.com/googleapis/synthtool/blob/0dcf73928241fa27d7768e14c435e3d9f526beac/synthtool/languages/java.py#L474)
- java.common_templates uses [`_common_template_metadata()`](https://github.com/googleapis/synthtool/blob/0dcf73928241fa27d7768e14c435e3d9f526beac/synthtool/languages/java.py#L446), which looks up the latest Libraries BOM version:
  ```
    metadata["latest_bom_version"] = latest_maven_version(
        group_id="com.google.cloud",
        artifact_id="libraries-bom",
    )
  ```

My current idea: at

**Comment by chingor13** [comment]
Is this still an issue (it's OOSLO)? Most of the libraries have moved to the monorepo.

**Comment by suztomo** [comment]
The hermetic build process is going to take care of the libraries-bom version. Closing this issue that is on the postprocessor. Let's create another issue if the new process still has the same problem.
