### ISSUE TITLE
Python: Improve test performance by running tests in parallel

### ISSUE THREAD

**Issue by m-strzelczyk** [googleapis/synthtool#1364]
When working on code samples in Python language, I'm often irritated by how long it takes to run the full test suite for my PRs. I'd love to have support for `pytest-xdist` or `pytest-parallel` in the noxfiles that we force-sync in our Python repositories. All tests should always be written in a way, that they don't rely on any order and don't interfere with each other, so this should not cause any problems.

I'll provide a PR that supports those pytest extensions for review in a moment.

According to tests run on my local machine on the `python-compute` repository, the time it takes to run all tests for samples can be reduced to 5 minutes from almost half an hour IIRC.

**Comment by parthea** [comment]
Closed via https://github.com/googleapis/synthtool/pull/1365
