### ISSUE TITLE
Autosynth should not submit PRs where only 'synth.metadata' has changed.

### ISSUE THREAD

**Issue by tseaver** [googleapis/synthtool#139]
The 'bot submitted nineteen PRs to 'google-cloud-python' this morning, of which eighteen consisted of nothing more than changes to 'synth.metadata'.  `src/apply-change.ts` should exclude `synth.metada` from the list of candidate changes triggering PR creation.

**Comment by theacodes** [comment]
Fixed in internal change legit/102264
