### ISSUE TITLE
Can owlbot-java use the formatter defined in pom.xml?

### ISSUE THREAD

**Issue by suztomo** [googleapis/synthtool#1502]
We can eliminate the discrepancy between the two if owlbot-java uses the formatter defined in the project:

- https://github.com/googleapis/java-shared-config/blob/main/pom.xml#L239
- https://github.com/googleapis/synthtool/blob/master/docker/owlbot/java/bin/format_source.sh#L36 (the version is set at https://github.com/googleapis/synthtool/blob/master/docker/owlbot/java/Dockerfile#L29)

**Comment by chingor13** [comment]
We do not want to run any `mvn` commands in the post-processor that use code from the repository. owl-bot runs in a privileged (albeit limited) environment and you can craft a pom.xml such that it loads malicious plugins that run arbitrary code.

For this reason, we included the java formatter jar in the post-processor image and ran it directly.

**Comment by suztomo** [comment]
@chingor13 Thank you for the background. That's a good principle worth written down somewhere (my todo).
