### ISSUE TITLE
bug(python): Release script for python is failing with `No such file or directory: '.kokoro/requirements.txt'`

### ISSUE THREAD

**Issue by parthea** [googleapis/synthtool#1566]
See example failure here: https://fusion2.corp.google.com/invocations/5714116c-bad2-4d16-8e8e-d94ea7ec6280/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-securitycenter%2Frelease%2Frelease/log.

I think the path `kokoro/requirements.txt` here should be changed to `github/{{ metadata['repo']['repo'].split('/')[1] }}/kokoro/requirements.txt`
https://github.com/googleapis/synthtool/blob/037c0a98c6541954e73384a9089a38f1294adfa0/synthtool/gcp/templates/python_library/.kokoro/release.sh#L19

**Comment by SurferJeffAtGoogle** [comment]
@parthea I think your path fix will work.  Are you preparing a pull request?
