### ISSUE TITLE
owlbot-java: the switch of BOM introduction in README.md is unclear

### ISSUE THREAD

**Issue by suztomo** [googleapis/synthtool#1573]
Thanks for stopping by to let us know something could be better!

https://github.com/googleapis/java-datastream does not have BOM usage in README.md

https://github.com/googleapis/java-language has BOM usage in README.md

# Investigation

It seems that the template logic in synthtool's [README.md](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/README.md) uses `metadata['snippets'][metadata['repo']['api_shortname'] + '_install_with_bom']`. The `metadata['snippets']` object is created at https://github.com/googleapis/synthtool/blob/0dcf73928241fa27d7768e14c435e3d9f526beac/synthtool/languages/java.py#L463.

Whether the README has instruction to use the Libraries BOM or not depends on the existence of this tag

```
  <!-- [START speech_install_with_bom] -->
```

https://github.com/googleapis/java-speech/blob/0b1c6f22d874f2770656bc0e44a628a9583c4ee3/samples/snippets/pom.xml#L27.

https://github.com/googleapis/synthtool/blob/625f84c8c127112ac72eb9d8ea6c6e7784a72772/synthtool/gcp/snippets.py#L55 is responsible to find the tags.

CC: @blakeli0

**Comment by SurferJeffAtGoogle** [comment]
@suztomo This issue will pass out of SLO in 13 days.  Please update it or close it.

**Comment by suztomo** [comment]
Closing because we’re planning to move template to the google-cloud-java monorepo.
