### ISSUE TITLE
PRs with nothing by synth.metadata changes

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#168]
This morning I woke up to ~60 PRs that all follow the same pattern:
https://github.com/googleapis/nodejs-iot/pull/89/files

The PR added the following files (which shouldn't be added):
- `__pycache__/synth.cpython-36.pyc`

And checked in a change to the synth metadata.  Guessing these PRs shouldn't have happened :)

**Comment by theacodes** [comment]
All PRs have been closed. Working on a fix to prevent this from occurring again.

**Comment by theacodes** [comment]
Internal fix at legit/103650
