### ISSUE TITLE
Borked logging build:  suppressed 'blacken'

### ISSUE THREAD

**Issue by tseaver** [googleapis/synthtool#174]
See: https://github.com/googleapis/google-cloud-python/pull/6880

Running `synthtool` locally in `logging` against the current `master` of `google-cloud-python` produces no output except `synth.metadata`.

**Comment by theacodes** [comment]
@crwilcox can you look into this?

**Comment by busunkim96** [comment]
I believe this issue came up when I switched the `blacken` session to use 3.7. 
```
Session blacken skipped: Python interpreter 3.7 not found.
```
We've switched back to 3.6 and added a note not to change it until 3.7 is available in the image we use.
