### ISSUE TITLE
Update the readme installation instruction template to use builtin venv instead of virtualenv

### ISSUE THREAD

**Issue by Mariatta** [googleapis/synthtool#1769]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
In the readme file's "Installation", it instructs people to install `virtualenv`. This might have been a leftover from when Python 2 was still supported by client libraries. Now that most libraries support Python 3, we should use the built-in venv which doesn't require additional package installation. This will make it simpler and easier to use.

 **Describe the solution you'd like**

- Example: update the template from:

```
pip install virtualenv
virtualenv <your-env>
```

to

```
python3 -m venv <your-env>
```

- Find any mentions of virtualenv and use venv instead.

 **Describe alternatives you've considered**

The status quo

 **Additional context**

Example instruction where it tells people to use virtualenv.
https://github.com/googleapis/python-bigtable#maclinux

`venv` has been available since Python 3.3.
Most client libraries at this point support Python 3.7+, therefore it is safe to use `venv`.

According to @dandhlee , the templates are in:
- https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/README.rst
- https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_mono_repo_library/README.rst

**Comment by dandhlee** [comment]
Tony, could you help out with this?
