### ISSUE TITLE
Java templates not receiving renovate bot updates

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/synthtool#1786]
For example GraalVM 22.3.1 is up but renovate bot is not picking this up despite being confiigured at https://github.com/googleapis/synthtool/blob/43c709a188a1aaaf3778e77e25332b10ff9413e0/renovate.json#L11-L17

This line prevents all subdirectories from receiving renovate-bot updates:

https://github.com/googleapis/synthtool/blob/43c709a188a1aaaf3778e77e25332b10ff9413e0/renovate.json#L5

**Comment by SurferJeffAtGoogle** [comment]
I have to guess at what Takashi was thinking when we committed https://github.com/googleapis/synthtool/commit/b799784676305d366fbf09c28e649b5c0d173f23.

The Github Automation team decided to turn off renovate bot and rely on dependabot instead for updating dependencies.  Can you describe your use case?

**Comment by mpeddada1** [comment]
Thanks for the context @SurferJeffAtGoogle! In order to make our GraalVM builds more predictable, we tag our trampoline docker images with the graalvm version (as seen [here](https://github.com/googleapis/synthtool/blob/a86e18975db26d8e94055382c624d84643fafb86/synthtool/gcp/templates/java_library/.kokoro/presubmit/graalvm-native.cfg#L6) and [here](https://github.com/googleapis/synthtool/blob/a86e18975db26d8e94055382c624d84643fafb86/synthtool/gcp/templates/java_library/.kokoro/presubmit/graalvm-native-17.cfg#L6)). The renovate bot configuration referenced in the PR description helps automate this process for us by removing the need to create a manual change.

**Comment by SurferJeffAtGoogle** [comment]
Ok.  Even after spending a while reading https://docs.renovatebot.com/, I don't understand renovate bot's configuration language well at all.  Would you like to propose a change to the config?

**Comment by mpeddada1** [comment]
I was thinking we could use `includePaths` to explicitly opt-in select files instead of `ignorePaths`? https://docs.renovatebot.com/configuration-options/#includepaths. I can work on contributing a PR!

**Comment by mpeddada1** [comment]
@SurferJeffAtGoogle I put up a proposed change in https://github.com/googleapis/synthtool/pull/1789. Curious to know what you think?
