### ISSUE TITLE
[Owlbot/Java] Owlbot README updates for libraries-bom version incorrect

### ISSUE THREAD

**Issue by kolea2** [googleapis/synthtool#1844]
Hi, we've noticed the libraries-bom version owlbot picks for the README file in java-bigtable is mismatched/incorrect. See the following update: https://github.com/googleapis/java-bigtable/pull/1871/commits/f9464e26c6c9c6b4ff1f83e093e4350892845e52

It's adding two different versions, 26.20.0 and 26.21.0 in different places. I tried to fix it by hand but rerunning owlbot just reverted back to this incorrect state.

**Comment by SurferJeffAtGoogle** [comment]
@suztomo This issue will fall out of SLO in 6 days.

**Comment by suztomo** [comment]
Checking

**Comment by suztomo** [comment]
The template has

```
      <version>{{ metadata['latest_bom_version'] }}</version>
```

```
implementation platform('com.google.cloud:libraries-bom:{{metadata['latest_bom_version']}}')
```

They both reference the same value. The commit https://github.com/googleapis/java-bigtable/commit/f9464e26c6c9c6b4ff1f83e093e4350892845e52 does not make sense.

**Comment by suztomo** [comment]
Actually the first one comes from `{{ metadata['snippets'][metadata['repo']['api_shortname'] + '_install_with_bom'] }}` .

**Comment by suztomo** [comment]
That checkbox doesn't create a pull request. Why?

**Comment by suztomo** [comment]
Changed priority to avoid OOSLO alert.

**Comment by suztomo** [comment]
# Solution 

If the Maven configuration section is actually the same across split repo libraries, there's no point to use the value from `samples/snippets/pom.xml`.

Shall we replace the `{{ metadata['snippets'][metadata['repo']['api_shortname'] + '_install_with_bom'] }]` with actual Maven pom parts if that's the case?

Things to survey: among the split repositories that use the README.md template, which ones are ok to show the Maven configuration and which ones need customized code from `samples/snippets/pom.xml`?

**Comment by suztomo** [comment]
The owlbot postprocessor is being replaced with hermetic build process. Closing this issue.
