### ISSUE TITLE
Add logging info for versions for dependencies and versions.

### ISSUE THREAD

**Issue by andreamlin** [googleapis/synthtool#194]
For debugging and repro purposes, it's very helpful to know exactly which version of googleapis/discovery-artifacts-manager/artman were used by a run of synthtool.

Context: I'm just trying to recreate https://github.com/googleapis/google-cloud-java/pull/4527 locally, but I often have to try several different commit hashes before I can find the right commit hash for the discovery-artifacts-manager version used.

**Comment by theacodes** [comment]
Shouldn't this already be in `synth.metadata`? Example: https://github.com/googleapis/google-cloud-python/blob/master/spanner/synth.metadata#L5-L9

**Comment by theacodes** [comment]
In the PR you sent over: https://github.com/googleapis/google-cloud-java/pull/4527/files#diff-c96b317d5c2942a25d31f311e5cd7cf1

**Comment by JustinBeckwith** [comment]
Please let us know if this is still an issue!
