### ISSUE TITLE
Upload the docs somewhere

### ISSUE THREAD

**Issue by tswast** [googleapis/synthtool#201]
Could we upload the docs somewhere and link to from the README and repo configuration?

I find myself referencing the code to figure out what I can do for operations (move, replace, etc.).

**Comment by SurferJeffAtGoogle** [comment]
@tswast  Which docs?

**Comment by tswast** [comment]
The Sphinx reference docs for the `synthtool` Python module.

**Comment by SurferJeffAtGoogle** [comment]
I tried the sphinx tool for half an hour, and wasn't able to get it to generate any docs.  :-(
