### ISSUE TITLE
allow README generation to be skipped

### ISSUE THREAD

**Issue by bcoe** [googleapis/synthtool#209]
https://github.com/googleapis/google-api-nodejs-client has a fairly bespoke README.md file, which we don't want to be repeatedly rewritten when `synthtool` is run on the repo. We should provide a mechanism for turning off README generation.

**Comment by JustinBeckwith** [comment]
We have that!  It's the `excludes` property:
https://github.com/googleapis/google-api-nodejs-client/blob/master/synth.py#L27

**Comment by bcoe** [comment]
awesome, I’ll keep this open until I land a patch to exclude READMEs from the node client.

**Comment by bcoe** [comment]
addressed here: https://github.com/googleapis/google-api-nodejs-client/pull/1657
