### ISSUE TITLE
Run synthtool for each language as part of CI

### ISSUE THREAD

**Issue by busunkim96** [googleapis/synthtool#212]
We should run a generation for each language synthtool supports as part of CI to make sure synthesis succeeds.

**Comment by SurferJeffAtGoogle** [comment]
Synth would have to succeed for 7 apis in 7 languages, or the pendig PR would refuse to merge.  Synth for language/APIs breaks often due to bugs in the generator, changes in the API, etc.  I'm afraid that would make our CI/CD tests too noisy to be useful.
