### ISSUE TITLE
README generation will show fields even if not defined in .repo-metadata

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#217]
We have a few weird npm modules that don't have links to things like reference API docs or product docs.  An example of that is here:
https://github.com/googleapis/nodejs-proto-files/pull/171/files

If those fields aren't defined in `.repo-metadata.json`, the bullet points are still rendered into the README, just with a dead link.  Instead, synthtool should either:
- Make the fields required and throw if they're not defined or...
- Hide the markup they would be used to generate

**Comment by JustinBeckwith** [comment]
It was https://github.com/googleapis/nodejs-proto-files/

**Comment by bcoe** [comment]
this should now be addressed by: https://github.com/googleapis/synthtool/pull/214
