### ISSUE TITLE
Generate more descriptive PRs

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/synthtool#231]
Allo! The repos we oversee will frequently receive multiple-file updates where docs and method names change subtly. The code changes aren't in the part of the API we normally interact with, and sometimes, we're not familiar with the API in general, if it's completely autogenerated. I can't understand those changes as well as the author(s), and I'm concerned I could easily mistake something as just a straightforward change, and miss the part in the code where, e.g. "templateNamePath" is now "templateNamesPath", and break someone's code in the next release.

In the best case scenario, our repos would receive PRs from synthtool that use a title that describes exactly what has changed, and indicates if it's a breaking change, feature, or bug fix. I would guess that's tricky due to multiple commits being combined into a single synchronization commit. However, as a starting point, could the description and commit include the messages of the combined commits to the source repo? Other ideas welcome as well.

**Comment by busunkim96** [comment]
Hiya!

Thank you for the feature request.

Synthtool pulls protos from [googleapis/googleapis](https://github.com/googleapis/googleapis/tree/master/google). If you look there, every commit says `Synchronize new proto/yaml changes.` Information about the changes is lost when the proto files are copied from the internal repository out to GitHub. So at the moment, it won't 

I see two items in the OKRs for the Yoshi Team that are relevant here:
1. The commit message and contents for changes made to templates in synthtool are preserved across autosynth PRs. 
1. Document a plan to preserve context of changes from internal repositories to GitHub (googleapis and then language-specific repos).

Autosynth PRs with template updates will have a description of what those template changes are by the end of the quarter. Preserving information about code changes in the API is going to be a longer process, but is beginning this quarter.

**Comment by SurferJeffAtGoogle** [comment]
Yay!  This is a feature request for context-aware commits, which we just finished implementing.  Here's an example PR generated with context-aware commits:  https://github.com/googleapis/google-cloud-ruby/pull/6270

**Comment by stephenplusplus** [comment]
@SurferJeffAtGoogle it's beautiful 😍 Nice job!
