### ISSUE TITLE
Run lint on synth.py

### ISSUE THREAD

**Issue by busunkim96** [googleapis/synthtool#233]
Linters (Flake8 and Black) don't run by default on `synth.py` scripts.

**Comment by SurferJeffAtGoogle** [comment]
For people maintaining Java, PHP, C#, NodeJs, Ruby, and Go repos, `synth.py` is already a burden because it's written in a different language.  I don't want to increase the burden by asking them to install python linters.

**Comment by tmatsuo** [comment]
FYI,
with Trampoline V2, you can say something along the lines with "you only need Docker to run the tests"
