### ISSUE TITLE
Allow autosynth PRs to be rebased

### ISSUE THREAD

**Issue by dwsupplee** [googleapis/synthtool#277]
I noticed [the renovate bot PRs](https://github.com/googleapis/google-cloud-php/pull/2161) have the ability to check a box in order to rebase.

In order to get similar functionality right now, you need to close out the synth PR and trigger new ones or wait for the next batch. I could see something similar to the checkbox being a handy feature for us as well:

<img width="389" alt="Screen Shot 2019-08-09 at 10 51 11 AM" src="https://user-images.githubusercontent.com/2079879/62799056-a5237000-ba94-11e9-8680-f2d7663b8f9b.png">

- [x] checkbox test

**Comment by SurferJeffAtGoogle** [comment]
Given the current docket of issues, I don't think I'll have time to implement this feature request.   Assigning to reporter to implement if they have time.

**Comment by SurferJeffAtGoogle** [comment]
Actually, I have time for this now...
 [x] checbox test
