### ISSUE TITLE
Update existing autosynth PRs

### ISSUE THREAD

**Issue by blowmage** [googleapis/synthtool#333]
Autosynth PRs are not generated if an existing autosynth PR exists. And the existing autosynth PR is not updated with more recent synthtool changes. However, release PRs are updated when a new commit is merged to master. I would like to request that the autosynth PRs match the release-please process.

We have had several instances where a change was made and was known to be wrong. We hold off on merging the change until it is reverted, but the PR never changes. Having the PR change to reflect newer changes would help client teams track these changes more efficiently.

**Comment by JustinBeckwith** [comment]
@SurferJeffAtGoogle this may be a good thing to look at if you're looking to get more familiar with synthtool and autosynth :)

**Comment by SurferJeffAtGoogle** [comment]
Similar feature request:
https://github.com/googleapis/synthtool/issues/277
