### ISSUE TITLE
AUTOSYNTH_USE_SSH override does not work

### ISSUE THREAD

**Issue by busunkim96** [googleapis/synthtool#355]
Steps to replicate:

1. Run synthtool with googleapis-private (`private=True`). Synthtool clones googleapis-private with HTTPS and asks for a password (GitHub access token)
![image](https://user-images.githubusercontent.com/8822365/71383233-30a72480-2590-11ea-87e9-570d73514135.png)
3. Set environment variable `AUTOSYNTH_USE_SSH`
4. Re-run synthtool

Sometimes synthtool will _still_ use HTTPS and ask for a password instead of using SSH.

**Comment by SurferJeffAtGoogle** [comment]
What if just removed the AUTOSYNTH_USE_SSH environment variable entirely.  Would anything break?

**Comment by SurferJeffAtGoogle** [comment]
Please re-open if this issue is causing you pain.
