### ISSUE TITLE
Tracking of metadata files doing too much

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#360]
I was taking a look at the changes in the `synth.metadata` files, and noticed a few issues leading to giant file size.  Most of them are likely solved by respecting `.gitignore` before adding files to this list. 

1. Tracking `node_modules`.  For an example, see [here](https://github.com/googleapis/nodejs-logging/pull/660/files#diff-ca17b2e3ad979a60178c47d8297d674dR2597).  This directory is more a build time artifact, and is in the `.gitignore`.  There will be thousands (possibly tens of thousands) of files in this directory.

2. `build/` directory.  Again, this one is a build artifact and already in `.gitignore`. 

3. Tracking the `.git` directory.  See example [here](https://github.com/googleapis/nodejs-logging/pull/660/files#diff-ca17b2e3ad979a60178c47d8297d674dR110).  Similar to how git does it's default rules, we should likely ignore this directory by default.  

The synth PRs getting generated are creating giant files that we likely need to pair down.

**Comment by JustinBeckwith** [comment]
Bumping this to a P1.  Turns out when running `synthtool` locally, it's deleting files in the `.git` directory, which is leading to a corrupt git index. Maybe we want to roll this change back again :/

**Comment by bcoe** [comment]
Some inspiration, in the Node.js the files folks ignore are pretty standardized, so we eventually broke logic for exclude into a module ([test-exclude](https://www.npmjs.com/package/test-exclude))...

And then also broke this out into a [schema](https://github.com/istanbuljs/schema/blob/master/default-exclude.js) tldr; we should be able to figure out a comprehensive list of folders to ignore, and perfect this over time.
