### ISSUE TITLE
NodeJS: Document project settings

### ISSUE THREAD

**Issue by texasmichelle** [googleapis/synthtool#384]
**Is your feature request related to a problem? Please describe.**
When setting up a new environment for the first time, I receive a small number of test failures. I am using my own GCP project, not long-door-651.
 **Describe the solution you'd like**
Documented steps for setting up a GCP project for testing, ideally in a way that can be automated for quickly creating a new environment.

1. Script or commands for creating a service account with necessary permissions
1. Command for copying resources to GCS buckets
1. Any other required setup 

 **Describe alternatives you've considered**
Providing access to individual developers would work, but doesn't scale well, especially to non-Googlers.
 **Additional context**
First identified while trying to resolve a user ticket. Details in [this PR](https://github.com/googleapis/nodejs-translate/pull/424).

**Comment by bcoe** [comment]
@texasmichelle I think there's a larger conversation that would be good to kick off here, how difficult it is to setup a testing environment varies greatly on a library by library basis; clearly documenting goals for configuring a sample test environment, like we document our code sample format, would be awesome.

**Comment by texasmichelle** [comment]
There is a need for this in python as well, since @steffnay and I recently ran into this while trying to run tests locally. [These tests](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/vision/cloud-client/product_search/product_search_test.py) also fail unless you use a service account in the python-docs-samples-tests project.
