### ISSUE TITLE
Node.js, add environment variable file to .kokoro

### ISSUE THREAD

**Issue by bcoe** [googleapis/synthtool#388]
We should figure out a reasonable approach to managing environment variables, such that new environment variables can be added as needed [see](https://github.com/googleapis/nodejs-secret-manager/pull/34).

The [nodejs-docs-samples use a common build.sh file](
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/.kokoro/build.sh), I think we could do something similar, perhaps it's enough to simply allow folks to start adding some additional environment to our sample test shell file.

CC: @grayside, @sethvargo

**Comment by SurferJeffAtGoogle** [comment]
Are the contents of the environment variable secret?  Should they be available to both Kokoro and Github actions?

**Comment by bcoe** [comment]
@SurferJeffAtGoogle I think we'd want to avoid having any secrets set in this category of environment variable, it's mostly project names, etc.

Great point, we would want it to work in both GitHub actions and kokoro.

**Comment by sethvargo** [comment]
Well you're in luck if you choose Secret Manager then: https://github.com/GoogleCloudPlatform/github-actions/tree/master/get-secretmanager-secrets

**Comment by SurferJeffAtGoogle** [comment]
What's wrong with the  current solution of setting environment variables in build.sh?

**Comment by SurferJeffAtGoogle** [comment]
Please re-open if this is still important.
