### ISSUE TITLE
s.copy excludes does not work with directories

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#424]
I have a synthtool like this:

```
import synthtool as s
import synthtool.gcp as gcp
import logging
logging.basicConfig(level=logging.DEBUG)
common_templates = gcp.CommonTemplates()
templates = common_templates.node_library()
s.copy(templates, excludes=[
  '.eslintignore',
  '.eslintrc.yml',
  '.prettierignore',
  '.prettierrc',
  '.nycrc',
  'README.md',
  '.github/release-please.yml',
  '.kokoro/',
  '.github/workflows/',
  'codecov.yaml'
])
```

When I run it, the `.kokoro` directory is still copied over :( I would like to exclude it.

**Comment by busunkim96** [comment]
One workaround is to supply a full glob-style pattern (e.g., `.kokoro/**/*.cfg`)

**Comment by SurferJeffAtGoogle** [comment]
Can you provide a way to reproduce the issue?

I tried reproducing it with a test, but the test passes:
https://github.com/googleapis/synthtool/compare/master...SurferJeffAtGoogle:fix424?expand=1

**Comment by SurferJeffAtGoogle** [comment]
Closed due to inactivity.
