### ISSUE TITLE
Lint fails on Windows on end of line break

### ISSUE THREAD

**Issue by summer-ji-eng** [googleapis/synthtool#464]
Problem:
googleapis/gcs-resumable-upload ci/windows fail due to linter issue of end of line break style for windows (see [here](https://github.com/googleapis/gcs-resumable-upload/pull/329/commits/fe6d378d4a10bdf929e3bbb75174211aef3a52db#diff-cd02b9e0b731a6a1dedefed142f4419b))

To temporary unblock me, I removed `posttest` in package.json, [here](https://github.com/googleapis/gcs-resumable-upload/blob/fda3d3cef3c97f2e605b77574e6c84c73d2f6b51/package.json#L17)

Fix Suggestion from @bcoe: 
Instead of add .gitattribute to elf in single repo gcs-resumable-upload for windows ([example](https://github.com/googleapis/gcs-resumable-upload/pull/329/files/fda3d3cef3c97f2e605b77574e6c84c73d2f6b51#diff-fc723d30b02a4cca7a534518111c1a660)), 

maybe in `.github/workflows/ci.yaml` , add one extra command for windows that just does:
```run: print "*.ts text eol=lf\n*.js test eol=lf" > .gitattributes```

#### Steps to reproduce

  1. add ```"posttest": "npm run lint",``` in repo package.json

Feel free to @summer-ji-eng  if you have any question. Thanks!

**Comment by bcoe** [comment]
@SurferJeffAtGoogle great question, I bet that's just a rule we could turn off.

**Comment by summer-ji-eng** [comment]
The rule to turn off could be `// eslint-disable linebreak-style`

**Comment by bcoe** [comment]
@summer-ji-eng we could look at turning this off by default, I think that might be a good idea.

**Comment by summer-ji-eng** [comment]
> @summer-ji-eng we could look at turning this off by default, I think that might be a good idea.

To turn it off by default, one way is add `.gitattributes`(example) in nodejs template (this directory). @bcoe @SurferJeffAtGoogle LMK, if it is ok, I could sent the PR.

**Comment by summer-ji-eng** [comment]
resolved in #647
