### ISSUE TITLE
Autosynth places all commit text into title

### ISSUE THREAD

**Issue by jskeet** [googleapis/synthtool#467]
Sample PR: https://github.com/googleapis/google-cloud-dotnet/pull/4792

And the commit within it: https://github.com/googleapis/google-cloud-dotnet/pull/4792/commits/07bfbb9cda6af245ba836880622858ce4d016d01

Original commit in googleapis: https://github.com/googleapis/googleapis/commit/3d52f3c126fbfc31f067a7f54737b7f0dfbce163

Commit after I did a squash-and-merge to fix up the text: https://github.com/googleapis/google-cloud-dotnet/commit/5a41fb5f1c7f5329cc981b77cae1f4762d705002

The original commit message should be copied into the PR and commit created by autosynth, including line breaks. (I'm not quite sure whether the line breaks ended up being stripped explicitly, or whether something's removing them accidentally on the way.)

**Comment by busunkim96** [comment]
@SurferJeffAtGoogle Could you triage this issue?

**Comment by jskeet** [comment]
I can do that - it's been fixed :)

**Comment by jskeet** [comment]
(I'll reopen just to add appropriate labels though)

**Comment by jskeet** [comment]
Except it turns out I can't do that. I have permission to close the issue, but not edit labels. Reclosing, but Jeff will have to fix the labels.
