### ISSUE TITLE
Node.js PR proposing outdated files

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#482]
So this is a weird one:
https://github.com/googleapis/nodejs-googleapis-common/pull/253

The PR is proposing we add a `.eslintrc.yml`, which we deleted from the list of available files:
- https://github.com/googleapis/synthtool/tree/master/synthtool/gcp/templates/node_library
- https://github.com/googleapis/synthtool/pull/463

It is also proposing an old copy of `.github/ci.yaml` here:
https://github.com/googleapis/nodejs-googleapis-common/pull/253/files#diff-60fe268f71ae7f8409aff40d0a3e51d8R12

When that file was modified to not include nodejs 8 here:
https://github.com/googleapis/synthtool/commit/1b4cc80a7aaf164f6241937dd87f3bd1f4149e0c

I suspect it's because we're using context aware commits :) You can see we have 5 commits here:
https://github.com/googleapis/nodejs-googleapis-common/pull/253/commits

**Comment by bcoe** [comment]
this is what I was seeing the other day too, here's another:

https://github.com/googleapis/release-please/pull/406/files

**Comment by SurferJeffAtGoogle** [comment]
@sofisl

I understand what's happening.

In https://github.com/googleapis/nodejs-googleapis-common/commit/0a8d6e1250dab02dde74397b3118c3759d01557d, Sofia manually changed some files that are usually generated by the templates.

So when autosynth runs synthtool at 0a8d6e1250dab02dde74397b3118c3759d01557d to see if any generated files changed, it actually uses an old (from 3/22) version of the synthtool templates: 7e98e1609c91082f4eeb63b530c6468aefd18cfd.  nodejs/googleapis/common's final line of code: https://github.com/googleapis/nodejs-googleapis-common/blob/cce74ba85906e6e723a2bb8a4fc2fae7b81a3a33/synth.py#L23 overwrites all Sofia's changes.  Git never sees a merge conflict.

I'm considering possible solutions...

**Comment by SurferJeffAtGoogle** [comment]
@chingor13 

Jeff, I think I've seen this in Java PRs too.

**Comment by bcoe** [comment]
thanks for digging into this.

**Comment by SurferJeffAtGoogle** [comment]
Fixed in Autsynth PR # 148351.
