### ISSUE TITLE
Error running synthtool in autosynth for nodejs-kms

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#491]
Woke up this morning to this fella:
https://github.com/googleapis/nodejs-kms/issues/315

Running locally, I can confirm that error happens, but I have no idea why.  I made a bunch of other changes, ran synthtool locally again, and it seems to be fine.  🤷

**Comment by SurferJeffAtGoogle** [comment]
synthtool leaves the a commit hash in synth.metadata.  The next run of synthtool, it expects to find the same commit hash in the repo.

In the case of googleapis/nodejs-kms#315, that commit hash was *not* in the repo history.

**Comment by JustinBeckwith** [comment]
So this is an interesting problem!  We often run `synthtool` locally.  Sometimes, the commits on the local git repo may not match what happens after a squash or local rebase.  

Lots of this happens not by the robot:
https://github.com/googleapis/nodejs-kms/commits/master/synth.metadata

Is it possible we shouldn't update synth  metadata outside of the autosynth environment?

**Comment by SurferJeffAtGoogle** [comment]
Fixed in Autosynth change 148356.

> Is it possible we shouldn't update synth metadata outside of the autosynth environment?

Running synthtool manually should update synth.metadata.  I hadn't expected people to run synthtool manually on a commit that was ultimately not merged into github.  I added code to cope with that situation.
