### ISSUE TITLE
Autosynth git cloning should be recursive

### ISSUE THREAD

**Issue by jskeet** [googleapis/synthtool#509]
When autosynth clones github repos, it currently doesn't include submodules.

That could easily make a build/generation process fail - code within a repo typically expects everything to be present. It's currently not actually causing us a problem on google-cloud-dotnet, other than a warning, but it's a bit of a "gotcha".

**Comment by busunkim96** [comment]
@SurferJeffAtGoogle Could you triage this? Thank you!
