### ISSUE TITLE
Improve autosynth logging

### ISSUE THREAD

**Issue by chingor13** [googleapis/synthtool#540]
Currently, it is very difficult or impossible to figure out what happened during an autosynth run.

Ideally, the main autosynth log (from `autosynth.multi`) show something like:
```
[time] - [log level] - Generating X client
[time] - [log level] -   Created PR: https://link/to/pull/request
[time] - [log level] -   Autosynth failed, opening issue: https://link/to/issue
[time] - [log level] - Generating Y client
[time] - [log level] -   Created PR: https://link/to/pull/request
[time] - [log level] -   Autosynth failed, opening issue: https://link/to/issue
```
- There should be a root xunit XML log where each entry is each execution of `python3 -m autosynth.synth`
- Each execution of `python3 -m autosynth.synth` should be captured in a log file and available for debugging.
- Each execution of `python3 -m autosynth.synth` should create a xunit XML log where each entry is an execution of `python3 -m synthtool`
- Each execution of `python3 -m synthtool` should be captured in a log file and available for debugging.
- We should be able to see every command invocation for debugging.

**Comment by SurferJeffAtGoogle** [comment]
The logs that we see now in bug reports like this one look great!
https://github.com/googleapis/nodejs-recommender/issues/80

However, IIRC, fusion used to report the result of every API generation here:
https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava/KOKORO/568dd2ec-07da-4a8a-80bd-f5598a72f156/1591691423323/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava%20build%20%23801/Targets?target=cloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava&drilldownTab=tests

But I no longer see it.

**Comment by chingor13** [comment]
I think the `sponge_log.xml` got too big - it's available in placer and looks ok. We might need to exclude the successful build logs since we probably only care about the failures.

**Comment by SurferJeffAtGoogle** [comment]
One design chingor13 was considering was having the logger instance contain 2 handlers - one for stdout and one for a file log. The file log would be the sponge_log.log and contain debug+ logs while stdout would only show info+ levels.
