### ISSUE TITLE
Synthesis failed for java-spanner due to insufficient memory

### ISSUE THREAD

**Issue by skuruppu** [googleapis/synthtool#545]
#### Environment details

  - OS: Linux
  - Python version: 3.6.9
  - pip version: 18.1
  - `synthtool` version: at commit ab883569eb0257bbf16a6d825fd018b3adde3912

#### Problem

Autosynth has been unable to regenerate java-spanner (https://github.com/googleapis/java-spanner/issues/191) for a week. The error message is:

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 247463936, 0) failed; error='Not enough space' (errno=12)
...
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 247463936 bytes for committing reserved memory.
```

**Comment by SurferJeffAtGoogle** [comment]
Thank you for reporting this issue.

@chingor13 submitted a fix last night.  We expect the next autosynth run to succeed.

**Comment by chingor13** [comment]
Somehow autosynth is not using the per-source branch and is falling back to using the plain `autosynth`. It's trying to open 2 PRs from the same branch which GitHub is rejecting.

**Comment by chingor13** [comment]
When using multiple PRs, if any of the sources fails (generation or communicating with GitHub), we fall back to generating with a single PR, but we don't check if there's already an open pull request for that branch. This causes the fallback case to fail if a pull request is already open for that branch.

**Comment by chingor13** [comment]
Sorry, those comments were for the most recent spanner failure: https://github.com/googleapis/java-spanner/issues/210
