### ISSUE TITLE
Unintended debug log line in autosynth

### ISSUE THREAD

**Issue by jskeet** [googleapis/synthtool#546]
This isn't quite a duplicate of #540, as it's a specific bug with the current logging.

Looking in the autosynth logs, I've got a lot of this:

```text
2020-05-13 07:24:04,390 autosynth [DEBUG] > Running: {' '.join(command)}
```

I suspect the intention is to log the *result* of calling `join`.

I strongly suspect the code to fix is in `autosynth/executor.py`, but I don't know enough Python to make the fix myself in the most Pythonic way.

**Comment by chingor13** [comment]
Yeah, we missed the `f` to make it use string interpolation.
