### ISSUE TITLE
Update sphinx conf.py for > 3.0.0

### ISSUE THREAD

**Issue by crwilcox** [googleapis/synthtool#570]
Update templates to incorporate change seen at https://github.com/googleapis/python-bigtable/pull/20

https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/docs/conf.py.j2
https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/noxfile.py.j2

**Comment by crwilcox** [comment]
@kolea2

**Comment by SurferJeffAtGoogle** [comment]
I don't have enough context to understand the problem alluded to in this bug description.

**Comment by crwilcox** [comment]
We were forced to pin sphinx due to a breaking change in 3.0.0+. This change has already been made in Bigtable, but other libraries will likely want the same change.

**Comment by SurferJeffAtGoogle** [comment]
I see, so this bug is really a for-all-the-python-libraries bug?  It seems orthogonal to synthtool.
