### ISSUE TITLE
Support default version for Node library's system-test

### ISSUE THREAD

**Issue by summer-ji-eng** [googleapis/synthtool#584]
https://github.com/googleapis/nodejs-web-risk/pull/162

Problem:
As side-effect of support multiple version for nodejs client library, the libraries with multiple versions' `system-test` test beta version instead of default version.

The cause is that, `synth.py` loop through version list to use `typescript-gapic-generator` to generate the library, so the `system-test` content is whatever the last item is. If the last one is `v1beta1`, the system-test test `v1beta1` [example](https://github.com/googleapis/nodejs-web-risk/pull/162)

**Comment by bcoe** [comment]
I believe we've unblocked the repos that were failing as a result of this? and have a plan for dealing with it moving forward?

**Comment by summer-ji-eng** [comment]
In short words:

Shorterm Fix: Rearrange order of generating library in `synth.py`
Longterm fix: Use `apis.json` to config arguments, and embed `synth.py` logic into synthtool.
