### ISSUE TITLE
autosynth not running for java-pubsublite

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/synthtool#595]
Autosynth was never triggered for https://github.com/googleapis/java-pubsublite/

As a result, the library version in the [README](https://github.com/googleapis/java-pubsublite/blob/master/README.md) and on the [cloud site](https://cloud.google.com/pubsub/lite/docs/reference/libraries) are lagging behind what's available on Maven Central.

**Comment by SurferJeffAtGoogle** [comment]
I confirmed that autosynth is twice-daily running java-pubsublite/synth.py, as in this recent [run](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fjava/KOKORO/e097839b-c695-4759-b48c-5a85f5e3c069/1591047010554/build%20%23785/Targets?target=github%2Fsynthtool&drilldownTab=tests).  And synth.py succeeds, with no changes.

Therefore, the [synth.py](https://github.com/googleapis/java-pubsublite/blob/master/synth.py) is not yielding the expected changes, for Java-specifc reasons, so I ask @chingor13  for help.

**Comment by anguillanneuf** [comment]
Asked @chingor13 for review [here](https://github.com/googleapis/java-pubsublite/pull/95). It may be caused by a bug in our POM files.

**Comment by anguillanneuf** [comment]
Hoping for #601 to fix renovate bot, and then wait for synthtool to regen README.
