### ISSUE TITLE
Remove usage of `repos.json`

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#645]
For node.js, python, and java [we currently use](https://github.com/googleapis/synthtool/blob/969a2340e74c73227e7c1638ed7650abcac22ee4/autosynth/providers/python.py#L46) [repos.json](https://github.com/googleapis/sloth/blob/master/repos.json) to identify all relevant repositories where autosynth should run.

We would like to [delete this file](https://github.com/googleapis/sloth/issues/730).  Thinking out loud - I'm not sure why we would need repos.json.  I was thinking that each repository that requires synth should own it's own processes for updating, and use a kokoro job on a cron to run `autosynth` instead of relying on a top level configuration.  There could be other answers :)

**Comment by sofisl** [comment]
@JustinBeckwith - This doesn't really have anything to do with synthtool, but [we do use repos.json](https://github.com/googleapis/repo-automation-bots/blob/d79849f04f44969b5044858be92466c6256018dd/packages/sync-repo-settings/src/sync-repo-settings.ts#L56) for sync-repo-settings bot. Not a big deal, but I think we'd need to replace it in some capacity to keep sloth running.

**Comment by JustinBeckwith** [comment]
Yup - I'm slowly running through every usage, and making sure we have a tracking bug like this one.

**Comment by JustinBeckwith** [comment]
Thank you!
