### ISSUE TITLE
Python: Sphinx hyperlinking failing due to not escaping underscores

### ISSUE THREAD

**Issue by larkee** [googleapis/synthtool#660]
The generated docstrings are causing docs failures due to not escaping underscores for Sphinx hyperlinking. I have to manually revert them. See: https://github.com/googleapis/python-spanner/pull/99/commits/1544b9487b8af953bef8928e0e16f9c2b26489d8

Example failure: https://source.cloud.google.com/results/invocations/e3f1b078-a511-4408-8e06-ae628f4e2aa3/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner%2Fpresubmit%2Fpresubmit/log

**Comment by busunkim96** [comment]
It looks like pandoc isn't properly converting the markdown into RST. I haven't explored this part of the code much, so I'm not entirely sure.

**Comment by parthea** [comment]
Hi @larkee , I'm going to close this issue as obsolete but please feel free to re-open it if the issue still exists.
