### ISSUE TITLE
Sample README templates are incorrect for samples in client libs

### ISSUE THREAD

**Issue by busunkim96** [googleapis/synthtool#663]
See https://github.com/googleapis/python-pubsub/pull/151/commits/f11d069e5813882d7baf49544a465b5fa0b07db1 for the manual changes that had to be made to the Pub/Sub samples

Things that need to be fixed:
* samples assume they're in python-docs-samples
* samples calculate the wrong relative path
* compatible Python versions list is out of date

CC @plamut

**Comment by SurferJeffAtGoogle** [comment]
@parthea, please re-open if your changes didn't fix this issue.
