### ISSUE TITLE
Avoid stomping on read-only files

### ISSUE THREAD

**Issue by tseaver** [googleapis/synthtool#67]
This usage pattern for fixups:

```python
s.replace(
    '**/*.py',
    <source string>,
    <target string>,
)
```

blows up for unrelated files (e.g., under `.nox/`) which are not writeable (e.g., symlinks into non-local Python installs).

We could:

- Harden `replace` so that it skips over files which aren't writeable.
- Allow the script to pass in a specific `root` to be used for expanding the globs.
- Or maybe document the syntax for globs such that `root` isn't needed?

**Comment by JustinBeckwith** [comment]
@theacodes any thoughts on this one?

**Comment by theacodes** [comment]
> Harden replace so that it skips over files which aren't writeable.

I like this, I also would like us to skip over things that are in `.gitignore`.

> Allow the script to pass in a specific root to be used for expanding the globs.

Can't we already do that by passing in `root/**/*.py`? or are you thinking of something else?

> Or maybe document the syntax for globs such that root isn't needed?

What would this look like?

**Comment by tseaver** [comment]
> Can't we already do that by passing in `"root/**/*.py"`? or are you thinking of something else?

Nope, I was just uncertain about the semantics of the `**` glob, which is why I suggested documenting them with an example that *didn't* use the bare form.

**Comment by busunkim96** [comment]
To clarify: 

`replace` should
* skip files that are not writeable
* skip files that are ignored by git

?
