### ISSUE TITLE
Lost installation documentation

### ISSUE THREAD

**Issue by chingor13** [googleapis/synthtool#691]
When merging with autosynth and shuffling the docs around, it seems we lost the documentation on how to install from head.

**Comment by SurferJeffAtGoogle** [comment]
For context, what larger goal are you working on that requires installing
from head?

**Comment by chingor13** [comment]
Trying to give guidance for a developer who wishes to make synth.py changes and test locally. There's no pip install instructions anywhere and so a person might try to install from pypi and get a very old version.
