### ISSUE TITLE
Provide a way to identify the version of synthtool I'm running

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#756]
Over in #735, we came to the conclusion that I'm somehow stuck on an old version of synthtool, despite following the instructions to the best of my python-challenged abilities.  The problem I have right now is - I have no way to know what version of Synthtool I'm running!  Running `synthtool --version` gives me a calver version, but the instructions tell me to install by cloning the repo, so the version seems to be stuck in time:

```
$ synthtool --version
2020.2.4
```

Thinking out loud - I could see two options here:
- Set up the repo to use release-please and autorelease, and start doing real releases
- Have `synthtool --version` emit both the version, and the latest git commit hash from which it's being run

**Comment by prakhargurunani** [comment]
@SurferJeffAtGoogle Can I take up this ?

**Comment by SurferJeffAtGoogle** [comment]
Obsolete.
