### ISSUE TITLE
Add a 'synthtool.patch' command

### ISSUE THREAD

**Issue by tseaver** [googleapis/synthtool#77]
To apply a git-style patch from a file on the filesystem.  E.g.:

```python
s.patch(patch_file='filename.patch')
```

Maybe it could also take the patch as a triple-quoted string:

```python
patch = '''\
--- a/spanner/google/cloud/spanner_v1/gapic/spanner_client_config.py
+++ b/spanner/google/cloud/spanner_v1/gapic/spanner_client_config.py
@@ -83,7 +83,7 @@ config = {
                     "retry_params_name": "default"
                 },
                 "PartitionQuery": {
-                    "timeout_millis": 3600000,
+                    "timeout_millis": 30000,
                     "retry_codes_name": "idempotent",
                     "retry_params_name": "default"
                 },
'''
s.patch(patch=patch)
```

**Comment by SurferJeffAtGoogle** [comment]
Infeasible.

**Comment by tseaver** [comment]
@SurferJeffAtGoogle I'm interested why you would think so?  We have a [pure-Python library](https://pypi.org/project/patch/) available for applying patchsets.  Diffs embedded in triple-quoted string constants would be way easier to read / reason about than a bunch of the complex `s.replace()` calls I've seen in many `owlbot.py` files.
