### ISSUE TITLE
synthtool misbehaving in Java client readme generation

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/synthtool#794]
I just merged in the [BQ v1.122.2 release PR](https://github.com/googleapis/java-bigquery/pull/784/files) and synthtool immediately generated [this PR](https://github.com/googleapis/java-bigquery/pull/790/files) to set the BQ version back to 1.122.1 in README. Ii have not seen this behavior in the past. PTAL. Thanks!

**Comment by chingor13** [comment]
We are seeing this because we now generate the README more often. The gradle/sbt install snippets are being managed by both synthtool and release-please. We should probably remove the release-please version replacement tags and let synthtool completely manage this file.

**Comment by busunkim96** [comment]
Assigning a type and priority to appease the bot. Please adjust as appropriate @chingor13.
