### ISSUE TITLE
introduce startTrackingObsoleteFiles()/stopTrackingObsoleteFiles()

### ISSUE THREAD

**Issue by bcoe** [googleapis/synthtool#812]
We have been bumping into issues with tools like linters, where they might touch files that are outside of the responsibility of the code generator.

This teaches synthtool to track files that are not actually its responsibility. This in turn makes it difficult to implement the deletion logic.

## Proposal

Introduce `startTrackingObsoleteFiles()` and `stopTrackingObsoleteFiles()` which you use to "stop tracking obsolete files" before an operation like `lint --fix`.

```python
s.startTrackingObsoleteFiles()
// run the generator.
// copy templates.
s.stopTrackingObsoleteFiles()
// run post-processing like linting.
```

**Comment by bcoe** [comment]
CC: @alexander-fenster, who I've talked to about this one.

**Comment by SurferJeffAtGoogle** [comment]
Obsolete.
