### ISSUE TITLE
Publish a docker image containing synth and synthtool

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#823]
so it's easier for our team members to use.

**Comment by prakhargurunani** [comment]
@SurferJeffAtGoogle I have worked with docker images. Can I take up this ?

**Comment by SurferJeffAtGoogle** [comment]
@prakhargurunani  Thank you for offering to help.

I attempted to create a docker image in the [unidocker](https://github.com/googleapis/synthtool/tree/unidocker) branch.  However, I hit the issue that sometimes when synthtool is invoked, it actually runs another docker container.  And while it's technically possible to run one docker container in another docker container, it opens a security hole that is too risky for our purposes.
