### ISSUE TITLE
Autosynth fails when the googleapis commit comment is too long

### ISSUE THREAD

**Issue by jskeet** [googleapis/synthtool#848]
I suspect this is due to Autosynth trying to put the whole of a commit message into the title of the PR

Context:

- [googleapis commit updating container.v1](https://github.com/googleapis/googleapis/commit/75d1324fff65abad6435e6d501e050439b5a616b)
- [Autosynth-generated issue for failing to merge into google-cloud-dotnet](https://github.com/googleapis/google-cloud-dotnet/issues/5570)

Final error message:

```text
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/googleapis/google-cloud-dotnet/pulls
```

Explanation earlier in the stack trace:

```text
 {'message': 'Validation Failed', 'errors': [{'resource': 'Issue', 'code': 'custom', 'field': 'title', 'message': 'title is too long (maximum is 256 characters)'}], 'documentation_url': 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'}
```

For the moment I'm going to create a PR for this manually, but I suspect we should revisit how Autosynth handles commit messages. (Personally I'd prefer the commit message to remain in multiple lines in the body instead of being concatenated in the title anyway. It makes multiple conventional commit messages easier to separate out for release notes.)

**Comment by dazuma** [comment]
This also appears to have been causing google-cloud-ruby to fail to synth container-v1. (https://github.com/googleapis/google-cloud-ruby/issues/8137)

I opened a PR (#863) to truncate the title as a stopgap for now, but I agree with @jskeet that what we really want is a bit more smarts in how autosynth parses the public description and separates it into PR title and body content.

**Comment by SurferJeffAtGoogle** [comment]
@dazuma merged https://github.com/googleapis/synthtool/pull/863

I believe this issue has been fixed.
