### ISSUE TITLE
Autosynth is not picking up upstream package name

### ISSUE THREAD

**Issue by sofisl** [googleapis/synthtool#851]
https://github.com/googleapis/nodejs-area120-tables/pull/12
https://github.com/googleapis/nodejs-analytics-data/pull/22
https://github.com/googleapis/nodejs-security-private-ca/pull/16/files

In all of these examples, synthtool proposes overwriting the import statement in the `system-test` file. That import statement gets its information from the `BUILD.bazel` file `package-name` (e.g., google3/third_party/googleapis/google/area120/tables/v1alpha1/BUILD.bazel). 

I have just been rerunning synthtool manually, and that seems to correct the problem, but I'm not sure why synthtool isn't picking up the correct value to begin with.

**Comment by SurferJeffAtGoogle** [comment]
@alexander-fenster in https://github.com/googleapis/nodejs-area120-tables/pull/12/files#diff-b8b10cbcdcc63998ee7a8df81c85fc453d3e2485367dabf4647a6e03a30266d5 we see this line:

```
const tables = require('@google/area120-tables');
```

incorrectly being replaced with this line:

```
const tables = require('tables');
```

Do you see how the nodejs microgenerator could generate the latter line?

Please re-assign this bug to me after you answer.

**Comment by busunkim96** [comment]
@alexander-fenster  @sofisl Is this bug still relevant?

**Comment by sofisl** [comment]
@busunkim96, I don't think so, thanks for the reminder!
