### ISSUE TITLE
nodejs synth failing with   94:48  error  'window' is not defined  no-undef

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#853]
Autosynth failed for roughly half the nodejs libraries on 2020-11-17.

Example: https://fusion.corp.google.com/runanalysis/test/prod:cloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs-shard5/prod:cloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs-shard5/KOKORO/81fcf2f0-5694-446e-b0e5-6dfe543c8121/1605614947824/build%20%2389/Targets?target=cloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs-shard5&drilldownTab=tests

![image](https://user-images.githubusercontent.com/11778530/99419467-00a3f680-28b1-11eb-8f99-d743e4275d20.png)

```
2020-11-17 04:24:16,856 synthtool [DEBUG] > Running fix...
DEBUG:synthtool:Running fix...

> @google-cloud/language@4.2.1 fix /home/kbuilder/.cache/synthtool/nodejs-language
> gts fix

version: 14

/home/kbuilder/.cache/synthtool/nodejs-language/src/v1/language_service_client.ts
  94:48  error  'window' is not defined  no-undef

/home/kbuilder/.cache/synthtool/nodejs-language/src/v1beta2/language_service_client.ts
  94:48  error  'window' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by alexander-fenster** [comment]
I'm going to fix it in the generator.

**Comment by SurferJeffAtGoogle** [comment]
Last night's builds are green.  :-)
