### ISSUE TITLE
Race condition applying labels

### ISSUE THREAD

**Issue by jskeet** [googleapis/synthtool#897]
Context: https://github.com/googleapis/google-cloud-dotnet/pull/5825

History:

- yoshi-automation creates the PR
- yoshi-automation requests review
- google-cla applies "cla:yes" label
- yoshi-automation applies "context:full" label *and removes "cla:yes" label*
- google-cla re-applies "cla:yes" label and adds a comment saying that only it can change the label

It looks like this is just a race condition in terms of applying the context:full label... is there any reason it can't be applied during PR creation, rather than as a separate step? Or is that how the code looks internally and this is actually just a github internal race condition?

Note that everything resolved itself in the end, but it's a bit odd to look at. Very minor issue, but might be a symptom of something more important for future labels.

**Comment by chingor13** [comment]
Context: this uses update labels under the hood: https://github.com/googleapis/synthtool/blob/c2de32114ec484aa708d32012d1fa8d75232daf5/autosynth/change_pusher.py#L74-L76

It should instead add labels directly: https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#add-labels-to-an-issue

**Comment by SurferJeffAtGoogle** [comment]
Compared with my other priorities, I'm just never going to have time to fix this issue.
