### ISSUE TITLE
(java) remove_method not including docs above API

### ISSUE THREAD

**Issue by kolea2** [googleapis/synthtool#903]
Currently I have to work around removing the comments by adding another call to `remove_method`: https://github.com/googleapis/java-bigtable/pull/589/files#diff-296a39f9422dac004121c56b959022e9ad234263312c6433f8c58e2e6cd0b61eR130

This may be a special case for Bigtable since we have the concept of `'Base...'` classes - a purely generated class worked fine.

**Comment by lesv** [comment]
@kolea2 Is there any reason this should stay open?

**Comment by kolea2** [comment]
@lesv bigtable is still using autosynth/synthtool, so I believe so

**Comment by lesv** [comment]
@Neenu1995 @kolea2 Please close this when Bigtable moves to OwlBot

**Comment by kolea2** [comment]
All good here - thanks for the reminder :)
