### ISSUE TITLE
PHP autosynth failing with `error: cannot apply binary patch to 'Dlp/metadata/V2/Dlp.php' without full index line`

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#918]
https://fusion.corp.google.com/runanalysis/test/prod:cloud-devrel%2Fclient-libraries%2Fautosynth%2Fphp/prod:cloud-devrel%2Fclient-libraries%2Fautosynth%2Fphp/KOKORO/df06a580-bede-479d-aeeb-550c077e48a0/1611572173159/build%20%23936/Targets?target=logs%2FDlp&drilldownTab=logs

**Comment by SurferJeffAtGoogle** [comment]
Git thinks that some generated PHP files are binary.

@vam-google, the timing of this issue exactly matches the timing of https://github.com/googleapis/gapic-generator/issues/3334.  Do you think they're related?

**Comment by SurferJeffAtGoogle** [comment]
https://github.com/googleapis/synthtool/pull/928 will fix autosynth so it can handle the new binary output, but it leaves a question for @dwsupplee and @bshaffer: Do we actually want to generate binary php files?  The results are pull requests [like this](https://github.com/googleapis/google-cloud-php/pull/3709/files#diff-2803ea2e50652d02ad611ac48b30820fb6545ae5413acaead210f097ab0902f3) that are impossible to visually diff.

@vam-google, I see that the generator used to hex-encode the binary payload [like this](https://github.com/googleapis/google-cloud-php/blob/master/Dlp/metadata/V2/Dlp.php) but now injects raw binary into the php files [like this](https://github.com/googleapis/google-cloud-php/blob/ba340ee650fa4545051c47c61160c855b7332a60/Dlp/metadata/V2/Dlp.php?raw=true).  Was that a recent protobuf compiler change?  Was it intentional?

**Comment by dwsupplee** [comment]
@SurferJeffAtGoogle, it does look intentional based on: https://github.com/protocolbuffers/protobuf/pull/8006

I just tested the changes out and they do work, so I think we're okay to move forward with this for now. To your point, I don't love not being able to read the diff anymore and am interested in alternatives to this approach at some point in the future.

Thanks for resolving this for us!

**Comment by SurferJeffAtGoogle** [comment]
Thanks David.  I'll move forward with my fix in synthtool.
