### ISSUE TITLE
Support multiple `codeowner_team`s in `.repo-metadata.json`

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#946]
Today you can add a `codeowner_team` to `.repo-metadata.json`, and it will add that team as a CODEOWNER along side the language specific team.  There are cases where we want multiple teams, often both a DPE team and a product engineering team that need CODEOWERS access.  Ideally, `codeowner_team` would support both a string, and an array.  

Today, we would need to:
- hand modify the `CODEOWNERS` file
- Add `CODEOWNERS` to the ignore list `synth.py` when copying templates

**Comment by chingor13** [comment]
The current workaround is to specify both with a space in .repo-metadata.json. A list of strings would be better.

**Comment by parthea** [comment]
I'm going to close this issue as we're using the workaround, which is a space between the team names. This is the same syntax as the `CODEOWNERS` file itself.

**Comment by tswast** [comment]
@parthea I'm seeing in https://github.com/googleapis/python-bigquery-magics/pull/6 that we now have a `.github/blunderbuss.yml` file. Does using a space as a separator work with blunderbuss syntax? Seems they split into yaml items.
