### ISSUE TITLE
Snippet parser cannot handle duplicated region tags

### ISSUE THREAD

**Issue by chingor13** [googleapis/synthtool#961]
Duplicated region tags should append to the same tag (as an alternative to using the exclusion tags).

**Comment by chingor13** [comment]
cc @anguillanneuf

**Comment by SurferJeffAtGoogle** [comment]
Does the snippet parser code live in this repo?

**Comment by SurferJeffAtGoogle** [comment]
@chingor13 I don't understand this bug.  Can you provide more detail?

**Comment by chingor13** [comment]
A valid sample file can re-use a snippet tag multiple times in the file to concatenate the contents.

Example:
```
[START snippet_tag]
line 1
line 2
[END snippet_tag]

Lines to exclude

[START snippet_tag]
line 3
line 4
[END snippet_tag]
```

The resulting snippet for `snippet_tag` should be:
```
line 1
line 2
line 3
line 4
```

The current implementation would only return:
```
line 3
line 4
```
