### ISSUE TITLE
.tar.gz from bazel should not be copied into Python library repos

### ISSUE THREAD

**Issue by busunkim96** [googleapis/synthtool#989]
Example: https://github.com/googleapis/python-analytics-data/blob/master/google-analytics-data-v1alpha-py.tar.gz

Some, but not all python repos appear to have `.tar.gz` files copied into them via synthtool. This tar is the output of bazel build, but should not be copied into the repo itself.

CC @ikuleshov

**Comment by parthea** [comment]
@busunkim96 I'm going to close this issue as obsolete as I have't seen `tar.gz` files being created since we've migrated to owl bot. Please re-open it if you're still seeing the issue.
